### ISSUE TITLE
Recommend building project documentation in transfer-equivalency wiki 

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Sprint-2019-Detroit/transfer-equivalency#24]
Hi transfer equivalency Team! Great job at the Detroit Sprint! :)

I wanted to submit an Issue to encourage you to host your project documentation in the [transfer-equivalency wiki](https://github.com/SFDO-Sprint-2019-Detroit/transfer-equivalency/wiki).

To learn more about this process take a look at the [About wikis](https://help.github.com/en/articles/about-wikis) Github article.

**Comment by tiagoruivo** [comment]
I moved our docs to the Wiki. Closing this out. Thanks for the suggestion

**Comment by robertbwatson** [comment]
@tiagoruivo Thanks for doing this! I've been pretty busy over the past week and this week doesn't look much better, but I hope to circle back on this project soon to help figure out next steps.
