### ISSUE TITLE
Include Github links on README for Project Team

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Sprint-2019-Detroit/transfer-equivalency#25]
Please consider adding Github links to the README file under the Project Team section.

As an example: https://github.com/SFDO-Sprint-2019-Detroit/CumulusCI-Process-for-Customers-and-Partners#project-team

Doing so will help other members of our community connect with one another in Github.

You can find a list of all community members who attended the Detroit Sprint [here](https://github.com/orgs/SFDO-Sprint-2019-Detroit/teams/community).

**Comment by tiagoruivo** [comment]
Done. Thanks for the suggestion!
