### ISSUE TITLE
Write ERD and functionality description

### ISSUE THREAD

**Issue by tiagoruivo** [SFDO-Sprint-2019-Detroit/transfer-equivalency#5]

**Comment by tiagoruivo** [comment]
Also expand the object to have descriptions and add fields

**Comment by Ejsavage** [comment]
![image](https://user-images.githubusercontent.com/49795619/61140860-46210a00-a49a-11e9-9ed3-91aa81db7629.png)

**Comment by Ejsavage** [comment]
[heda_entity_relationship_diagram with Transfer Course.pdf](https://github.com/SFDO-Sprint-2019-Detroit/transfer-equivalency/files/3387102/heda_entity_relationship_diagram.with.Transfer.Course.pdf)

**Comment by Ejsavage** [comment]
[Blank Diagram.pdf](https://github.com/SFDO-Sprint-2019-Detroit/transfer-equivalency/files/3387321/Blank.Diagram.pdf)

**Comment by Ejsavage** [comment]
[Transfer Equivalency Architecture.pdf](https://github.com/SFDO-Sprint-2019-Detroit/transfer-equivalency/files/3387323/Transfer.Equivalency.Architecture.pdf)

**Comment by Ejsavage** [comment]
[Transfer Equivalency Architecture.pdf](https://github.com/SFDO-Sprint-2019-Detroit/transfer-equivalency/files/3387343/Transfer.Equivalency.Architecture.pdf)

**Comment by Ejsavage** [comment]
https://www.lucidchart.com/documents/view/79b6d018-5b1c-4d1b-b72e-5f32546285df/0

**Comment by tiagoruivo** [comment]
See Wiki for details. Closing the issue
